vim.g.mapleader = " "
vim.keymap.set("n", "<leader>wh", "<C-w>h", { desc = "move to window left" })
vim.keymap.set("n", "<leader>wj", "<C-w>j", { desc = "move to window below" })
vim.keymap.set("n", "<leader>wk", "<C-w>k", { desc = "move to window above" })
vim.keymap.set("n", "<leader>wl", "<C-w>l", { desc = "move to window right" })
vim.keymap.set("n", "<leader>ww", "<C-w>w", { desc = "cycle to next window" })
vim.keymap.set("n", "<leader>ws", "<C-w>s", { desc = "split window horizontally" })
vim.keymap.set("n", "<leader>wv", "<C-w>v", { desc = "split window vertically" })
vim.keymap.set("n", "<leader>wq", "<C-w>q", { desc = "close current window" })

vim.keymap.set("i", "jk", "<Esc>", { noremap = true, silent = true, desc = "Esc" })
-- vim.keymap.set("n", "<leader>h", "<cmd>nohlsearch<CR>", { desc = "cancel search highlight" })
vim.keymap.set({ "n", "v" }, "gl", "$", { desc = "goto line end" })
vim.keymap.set({ "n", "v" }, "gh", "^", { desc = "goto line start" })
vim.keymap.set({ "n", "v" }, "ge", "G", { desc = "goto last line" })
vim.keymap.set("v", "<leader>y", '"+y', { desc = "copy to clipboard" })
vim.keymap.set("n", "<leader>y", '"+yy', { desc = "copy to clipboard" })
vim.keymap.set("n", "<C-a>", "ggVG", { desc = "select all" })
vim.keymap.set("n", "<C-s>", ":w!<CR>", { desc = "write" })
vim.keymap.set("n", "<leader>L", "<cmd>lsp restart<CR>", { desc = "restart lsp" })
vim.keymap.set("n", "gj", "Lzz", { desc = "goto screen bottom" })
vim.keymap.set("n", "gk", "Hzz", { desc = "goto screen top" })
vim.keymap.set("x", "q", "<Esc>", { noremap = true, silent = true, desc = "Exit visual mode" })
vim.keymap.set("t", "<C-A-n>", "<C-\\><C-n>", { desc = "Terminal normal mode" })
